image: node:latest

stages:
  - testBuildDeploy

testBuildDeploy:
  stage: testBuildDeploy
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install --frozen-lockfile
    - pnpm test
    - pnpm build
    - pnpm add -D netlify-cli
    - npx netlify deploy --prod
