image: node:latest

stages:
  - testBuildDeploy

testBuildDeploy:
  stage: testBuildDeploy
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install --frozen-lockfile
    - pnpm setup
    - pnpm test
    - pnpm build
    - pnpm add -g netlify-cli
    - pnpm exec netlify deploy --prod
