image: node:latest

stages:
  - testBuildDeploy

testBuildDeploy:
  stage: testBuildDeploy
  script:
    - npm ci
    - npm run test
    - npm run build
    - npm install netlify-cli --save-dev
    - npx netlify deploy --prod
